### ISSUE TITLE
下载Emnist出现问题怎么办

### ISSUE THREAD

**Issue by gebilxs** [TsingZ0/PFLlib#176]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 113192/113192 [00:00<00:00, 252593.26it/s]
Traceback (most recent call last):
  File "emnist.py", line 94, in <module>
    generate_emnist(dir_path, num_clients, niid, balance, partition)
  File "emnist.py", line 50, in generate_emnist
    trainset = torchvision.datasets.EMNIST(
  File "/home/pai/envs/hdl-bfl/lib/python3.8/site-packages/torchvision/datasets/mnist.py", line 297, in __init__
    super().__init__(root, **kwargs)
  File "/home/pai/envs/hdl-bfl/lib/python3.8/site-packages/torchvision/datasets/mnist.py", line 99, in __init__
    self.download()
  File "/home/pai/envs/hdl-bfl/lib/python3.8/site-packages/torchvision/datasets/mnist.py", line 334, in download
    download_and_extract_archive(self.url, download_root=self.raw_folder, md5=self.md5)
  File "/home/pai/envs/hdl-bfl/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 434, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/pai/envs/hdl-bfl/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 155, in download_url
    raise RuntimeError("File not found or corrupted.")
RuntimeError: File not found or corrupted.

**Comment by TsingZ0** [comment]
This issue may caused by PyTorch, due to the mismatch of the MD5 checksum, see https://discuss.pytorch.org/t/inaturalist-download-crashes-towards-the-end/149006/6.

**Comment by gebilxs** [comment]
Thanks for you reply~
