### ISSUE TITLE
python generate_Flowers102.py noniid - pat时 报错

### ISSUE THREAD

**Issue by maxwellgodv** [TsingZ0/PFLlib#188]
您好，python generate_Flowers102.py noniid - pat时 报错

Traceback (most recent call last):
  File "/Users/macbookpro/PycharmProjects/PFLlib-master/dataset/generate_Flowers102.py", line 72, in <module>
    generate_Flowers102(dir_path, num_clients, niid, balance, partition)
  File "/Users/macbookpro/PycharmProjects/PFLlib-master/dataset/generate_Flowers102.py", line 60, in generate_Flowers102
    X, y, statistic = separate_data((dataset_image, dataset_label), num_clients, num_classes, 
  File "/Users/macbookpro/PycharmProjects/PFLlib-master/dataset/utils/dataset_utils.py", line 84, in separate_data
    num_per = num_all_samples / num_selected_clients
ZeroDivisionError: division by zero
请问如何解决，感谢您的回复！

**Comment by TsingZ0** [comment]
由于阶段性更新导致了代码不匹配，已修复
