### ISSUE TITLE
A bug in FedCAC

### ISSUE THREAD

**Issue by JACKSON1077** [TsingZ0/PFLlib#214]
FedCAC only consider full participation in per global training round right？Something went wrong when i set the join ratio like 0.3, 0.5(less than 1), but normal when the join ratio was set to 1, here are the error:

Traceback (most recent call last):
  File "PFLlib-master\system\main.py", line 549, in <module>
    run(args)
  File "PFLlib-master\system\main.py", line 376, in run
    server.train()
  File "PFLlib-master\system\flcore\servers\servercac.py", line 31, in train
    self.send_models()
  File "PFLlib-master\system\flcore\servers\servercac.py", line 120, in send_models
    self.get_customized_global_models()
  File "PFLlib-master\system\flcore\servers\servercac.py", line 85, in get_customized_global_models
    torch.abs(self.clients[i].critical_parameter.to(self.device) - self.clients[j].critical_parameter.to(self.args.device))
AttributeError: 'NoneType' object has no attribute 'to'

the command i run is：
python -u main.py -lbs 10 -nc 20 -jr 0.5 -nb 100 -data Cifar100 -m cnn -algo FedCAC -gr 3 -did 0 -go cnn -tau 0.5 -bt 170

**Comment by TsingZ0** [comment]
Please see #215 for reference.
