### ISSUE TITLE
FedCP训练结果无法保存

### ISSUE THREAD

**Issue by Felix89-ui** [TsingZ0/PFLlib#221]
Best global accuracy.
0.9154948350549816

Average time cost per round.
73.17894887685776

Average time cost: 14716.38s.
Traceback (most recent call last):
  File "main.py", line 534, in <module>
    run(args)
  File "main.py", line 398, in run
    average_data(dataset=args.dataset, algorithm=args.algorithm, goal=args.goal, times=args.times)
  File "/root/autodl-tmp/PFLlib-master1/system/utils/result_utils.py", line 24, in average_data
    test_acc = get_all_results_for_one_algo(algorithm, dataset, goal, times)
  File "/root/autodl-tmp/PFLlib-master1/system/utils/result_utils.py", line 39, in get_all_results_for_one_algo
    test_acc.append(np.array(read_data_then_delete(file_name, delete=False)))
  File "/root/autodl-tmp/PFLlib-master1/system/utils/result_utils.py", line 47, in read_data_then_delete
    with h5py.File(file_path, 'r') as hf:
  File "/root/miniconda3/lib/python3.8/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/root/miniconda3/lib/python3.8/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '../results/Cifar10_FedCP_test_0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by TsingZ0** [comment]
Fixed in the latest version.

**Comment by Felix89-ui** [comment]
谢谢
